import { ClientItem, StatItem } from "@/types";

export const clientsData: ClientItem[] = [
  {
    id: "cl-1",
    name: "Tier-1 Integrated Steel Producer",
    sector: "Steel & Integrated Plants",
    location: "Eastern India",
    engagement: "L2 Automation Consulting & Mill Modernization",
    isRepresentative: true,
    statusBadge: "Strategic Engagement",
  },
  {
    id: "cl-2",
    name: "Major Long & Flat Products Mill",
    sector: "Steel & Integrated Plants",
    location: "Western India",
    engagement: "Bar Mill Tracking & Specialized Spares Sourcing",
    isRepresentative: true,
    statusBadge: "Multiple Mill Sites",
  },
  {
    id: "cl-3",
    name: "Leading Alloy & Heavy Rail Plant",
    sector: "Steel & Integrated Plants",
    location: "Central India",
    engagement: "Reheating Furnace Modeling & Roll Force Calculations",
    isRepresentative: true,
    statusBadge: "Long & Flat Products",
  },
  {
    id: "cl-4",
    name: "Primary Continuous Rebar Mill",
    sector: "International",
    location: "Sultanate of Oman",
    engagement: "Rolling Mill Level-2 Upgrade & TC Roll Rings Supply",
    isRepresentative: true,
    statusBadge: "International Plant",
  },
  {
    id: "cl-5",
    name: "Integrated Wire Rod Facility",
    sector: "Steel & Integrated Plants",
    location: "Eastern India",
    engagement: "Finishing Block Speed Cascade & Wire Rod Telemetry",
    isRepresentative: true,
    statusBadge: "Process Modernization",
  },
  {
    id: "cl-6",
    name: "Specialty Alloy Steels Producer",
    sector: "Process Industries",
    location: "Southern India",
    engagement: "Alloy Steel Billet Tracking & Sensor Calibration",
    isRepresentative: true,
    statusBadge: "Alloy & Special Steels",
  },
  {
    id: "cl-7",
    name: "Precision Rolling & Tube Works",
    sector: "Process Industries",
    location: "Western India",
    engagement: "Hydraulic AGC Servo Valve Testing & Consumables",
    isRepresentative: true,
    statusBadge: "Precision Rolling",
  },
  {
    id: "cl-8",
    name: "Gulf Heavy Rolling Mill Operations",
    sector: "International",
    location: "United Arab Emirates",
    engagement: "Imported Heavy Mill Machinery & Spares Consignments",
    isRepresentative: true,
    statusBadge: "Cross-Border Trading",
  },
];

export const companyStats: StatItem[] = [
  {
    id: "stat-1",
    label: "Years of Engineering Experience",
    value: 15,
    suffix: "+",
    description: "Deep domain focus in process industries and rolling mills",
  },
  {
    id: "stat-2",
    label: "Industrial Projects Commissioned",
    value: 45,
    suffix: "+",
    description: "Across domestic integrated steel plants and overseas facilities",
  },
  {
    id: "stat-3",
    label: "Rolling Mill Cobble Reduction",
    value: 35,
    suffix: "%",
    description: "Average customer improvement through L2 setpoint accuracy",
  },
  {
    id: "stat-4",
    label: "High-Speed Delivery Speeds",
    value: 110,
    suffix: " m/s",
    description: "Proven Level-2 synchronization for wire rod finishing blocks",
  },
];
