import { ClientItem, StatItem } from "@/types";

export const clientsData: ClientItem[] = [
  {
    id: "cl-1",
    name: "Tata Steel Group",
    sector: "Steel & Integrated Plants",
    location: "Jamshedpur / Kalinganagar",
    engagement: "L2 Automation Consulting & Mill Modernization",
    isRepresentative: true,
    statusBadge: "Strategic Engagement",
  },
  {
    id: "cl-2",
    name: "JSW Steel Ltd.",
    sector: "Steel & Integrated Plants",
    location: "Vijayanagar / Dolvi",
    engagement: "Bar Mill Tracking & Specialized Spares Sourcing",
    isRepresentative: true,
    statusBadge: "Multiple Mill Sites",
  },
  {
    id: "cl-3",
    name: "Jindal Steel & Power (JSPL)",
    sector: "Steel & Integrated Plants",
    location: "Raigarh / Angul",
    engagement: "Reheating Furnace Modeling & Roll Force Calculations",
    isRepresentative: true,
    statusBadge: "Long & Flat Products",
  },
  {
    id: "cl-4",
    name: "Sohar Steel LLC",
    sector: "International",
    location: "Sultanate of Oman",
    engagement: "Rolling Mill Level-2 Upgrade & TC Roll Rings Supply",
    isRepresentative: true,
    statusBadge: "International Plant",
  },
  {
    id: "cl-5",
    name: "Electrosteel Steels",
    sector: "Steel & Integrated Plants",
    location: "Bokaro",
    engagement: "Finishing Block Speed Cascade & Wire Rod Telemetry",
    isRepresentative: true,
    statusBadge: "Process Modernization",
  },
  {
    id: "cl-6",
    name: "Kalyani Steels Ltd.",
    sector: "Process Industries",
    location: "Ginigera",
    engagement: "Alloy Steel Billet Tracking & Sensor Calibration",
    isRepresentative: true,
    statusBadge: "Alloy & Special Steels",
  },
  {
    id: "cl-7",
    name: "Sunflag Iron & Steel",
    sector: "Process Industries",
    location: "Bhandara",
    engagement: "Hydraulic AGC Servo Valve Testing & Consumables",
    isRepresentative: true,
    statusBadge: "Precision Rolling",
  },
  {
    id: "cl-8",
    name: "Gulf Heavy Industries",
    sector: "International",
    location: "United Arab Emirates",
    engagement: "Imported Heavy Mill Machinery & Spares Consignments",
    isRepresentative: true,
    statusBadge: "Cross-Border Trading",
  },
];

export const companyStats: StatItem[] = [
  {
    id: "stat-1",
    label: "Years of Engineering Experience",
    value: 15,
    suffix: "+",
    description: "Deep domain focus in process industries and rolling mills",
  },
  {
    id: "stat-2",
    label: "Industrial Projects Commissioned",
    value: 45,
    suffix: "+",
    description: "Across domestic integrated steel plants and overseas facilities",
  },
  {
    id: "stat-3",
    label: "Rolling Mill Cobble Reduction",
    value: 35,
    suffix: "%",
    description: "Average customer improvement through L2 setpoint accuracy",
  },
  {
    id: "stat-4",
    label: "High-Speed Delivery Speeds",
    value: 110,
    suffix: " m/s",
    description: "Proven Level-2 synchronization for wire rod finishing blocks",
  },
];
